//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int reportId { get; set; }
        public int taskId { get; set; }
        public System.DateTime date { get; set; }
        public string Info { get; set; }
        public double time { get; set; }
    
        public virtual task task { get; set; }
    }
}
