//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeSpentPerTask
    {
        public int clientId { get; set; }
        public string clientName { get; set; }
        public int projectId { get; set; }
        public string projectName { get; set; }
        public int taskId { get; set; }
        public string taskName { get; set; }
        public Nullable<double> spentTime { get; set; }
    }
}
